fix: add @type for this.setStream
Refs: https://github.com/saebekassebil/microphone-stream/issues/39#issuecomment-772703622
Fixes error TS9005: Declaration emit for this file requires using private name 'setStream'